# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01db22340212ce1ef038f3d3e301db4077eae1c23cb2c645af8c901677d424d3480ef051f0530f3466e3c3b0daceb0cf268c1e12eefe37929d50bf945aa7736

test:
  secret_key_base: 7bb6c610091e7f60ac1bbc8716045afad51152eea11ade1e70add9b4eede38f90c14cce0524f0f50536db7d8c18162eeea3357e2151842d893f2bac156f9e1f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
